team:
  name: default
  description: Default Nolan team with standard workflow
  version: 1.0.0
  agents:
  - name: ana
    output_file: research.md
    required_sections:
    - '## Problem'
    - '## Findings'
    - '## Recommendations'
    file_permissions: restricted
    workflow_participant: true
    awaits_qa: false
  - name: bill
    output_file: plan.md
    required_sections:
    - '## Overview'
    - '## Tasks'
    - '## Risks'
    file_permissions: restricted
    workflow_participant: true
    awaits_qa: true
    qa_passes: 1
  - name: carl
    output_file: progress.md
    required_sections:
    - '## Status'
    - '## Changes'
    file_permissions: restricted
    workflow_participant: true
    awaits_qa: true
    qa_passes: 1
  - name: dan
    output_file: NOTES.md
    required_sections:
    - '## Current Assignment'
    - '## Phase Status'
    - '## Handoff Log'
    file_permissions: permissive
    workflow_participant: false
    awaits_qa: false
  - name: enzo
    output_file: plan-review.md
    required_sections:
    - '## Summary'
    - '## Findings'
    - '## Recommendation'
    file_permissions: restricted
    workflow_participant: true
    awaits_qa: false
  - name: frank
    output_file: implementation-audit.md
    required_sections: []
    file_permissions: restricted
    workflow_participant: true
    awaits_qa: false
  workflow:
    coordinator: dan
    phases:
    - name: Research
      owner: ana
      output: research.md
      requires:
      - context.md
      template: Investigate and research the problem as described in context.md
    - name: Planning
      owner: bill
      output: plan.md
      requires:
      - research.md
      - context.md
      template: Create detailed implementation plan based on research findings
    - name: Plan Review
      owner: enzo
      output: plan-review.md
      requires:
      - plan.md
      - context.md
      - research.md
      template: Review implementation plan for feasibility, research alignment, architecture, and completeness
    - name: Implementation
      owner: carl
      output: progress.md
      requires:
      - plan.md
      - plan-review.md
      - context.md
      template: Implement changes following the approved plan
    - name: Implementation Audit
      owner: frank
      output: implementation-audit.md
      requires:
      - progress.md
      - context.md
      - research.md
      - plan.md
      - plan-review.md
      template: Audit implementation for code execution, security, integration, and plan compliance
