// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stats for a single agent session
 */
export type AgentSessionStats = { session_id: string, tmux_session: string, original_prompt: string, start_time: string, end_time: string, duration_secs: bigint, model: string, cost_usd: number, input_tokens: bigint, output_tokens: bigint, cache_read_tokens: bigint, cache_write_tokens: bigint, total_tokens: bigint, };
