// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSessionStats } from "./AgentSessionStats";
import type { DailyUsage } from "./DailyUsage";
import type { ModelUsage } from "./ModelUsage";

/**
 * Aggregated stats for an agent
 */
export type AgentStats = { agent_name: string, total_sessions: bigint, total_cost: number, total_tokens: bigint, total_duration_secs: bigint, avg_cost_per_session: number, avg_duration_secs: bigint, by_model: Array<ModelUsage>, by_date: Array<DailyUsage>, sessions: Array<AgentSessionStats>, };
