// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelUsage = { model: string, total_cost: number, total_tokens: bigint, input_tokens: bigint, output_tokens: bigint, cache_creation_tokens: bigint, cache_read_tokens: bigint, session_count: bigint, };
