organization:
  name: "Nolan"
  version: "1.0"
  description: "Autonomous Digital Business Platform"

  pillars:
    - id: "organizational-intelligence"
      name: "Organizational Intelligence"
      version_target: "V1"
      description: "Structure, governance, unlimited hierarchies"

    - id: "autonomous-operations"
      name: "Autonomous Operations"
      version_target: "V2"
      description: "Self-managing processes, event-driven orchestration"

    - id: "human-ai-collaboration"
      name: "Human-AI Collaboration"
      version_target: "V3"
      description: "Strategic direction, graduated autonomy"

  defaults:
    model: "sonnet"
    file_permissions: "restricted"
    escalation_timeout: "30m"
