policy:
  name: "default"
  version: "1.0"
  description: "Organization-level default policies"

  # Budget Controls
  budget:
    daily_limit: 10000        # Cents ($100/day)
    project_limit: 5000       # Cents ($50/project)
    alert_threshold: 0.8      # Alert at 80%

  # Model Allocation
  models:
    allowed:
      - opus
      - sonnet
      - haiku
    default: "sonnet"
    opus_requires_approval: false  # Future: require approval for Opus

  # Escalation Rules
  escalation:
    timeout: "30m"            # Agent stuck > 30 min
    budget_exceeded: "immediate"
    quality_failed:
      first_action: "retry"
      second_action: "escalate"
    paths:
      - "agent"
      - "team_coordinator"
      - "department_admin"
      - "organization_admin"

  # Execution Controls
  execution:
    max_concurrent_agents: 5
    max_retries: 3
    retry_delay: "5s"

  # Audit Requirements
  audit:
    log_decisions: true
    log_file_changes: true
    require_rationale: false  # Future: require rationale for changes
